apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: parsehub-backend
    newName: parsehubacr2026.azurecr.io/parsehub-backend
    newTag: latest
  - name: parsehub-frontend
    newName: parsehubacr2026.azurecr.io/parsehub-frontend
    newTag: latest

patches:
  - path: backend-patch.yaml
  - path: frontend-patch.yaml
  - path: configmap-patch.yaml
  - path: hpa-patch.yaml

commonLabels:
  environment: azure
